version: '3.8'

services:
  ask_app:
    depends_on:
      - ask_database
      - ask_redis
    build: .
    restart: always
    ports:
      - $APP_PORT:$APP_PORT
    networks:
      - ask_network
    env_file: ./.env
    environment:
      - MONGO_URI=mongodb://ask_database:27017/ask-now
      - REDIS_URI=redis://ask_redis:6379
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  ask_database:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    networks:
      - ask_network
    volumes:
      - data:/data/db

    ask_redis:
      image: redis:6.2.5-alpine
      restart: always
      ports:
        - '6379:6379'
      networks:
        - ask_network
      volumes:
        - redis_data:/data

networks:
  ask_network:

volumes:
  data:
  redis_data:
  node_modules:
