version: '3.8'

services:
  ask_app:
    depends_on:
      ask_database:
        condition: service_healthy
      ask_redis:
        condition: service_healthy
    build: .
    restart: unless-stopped
    ports:
      - $APP_PORT:$APP_PORT
    networks:
      - ask_network
    env_file: ./.env
    environment:
      - MONGO_URI=mongodb://ask_database:27017/ask-now
      - REDIS_URI=redis://ask_redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
      - node_modules:/app/node_modules

  ask_database:
    image: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    networks:
      - ask_network
    volumes:
      - data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo ask_database:27017/test --quiet
  ask_redis:
    image: redis:6.2.5-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - ask_network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]

networks:
  ask_network:

volumes:
  data:
  redis_data:
  node_modules:
